<?php

use Securepass\Securepass;

/**
 * Implements hook_permission().
 */
function securepass_permission() {
  return array(
    'administer securepass' =>  array(
      'title' => t('Administer securepass'),
      'description' => t('Administer Securepass configurations.'),
    ),
  );
}



/**
 * Implements hook_requirements().
 */
function securepass_requirements($phase) {
  $requirements = array();

  /*
   *  // Ensure translations don't break at install time
   *  $t = get_t();
   *
   *  // Report Drupal version
   *  if ($phase == 'runtime') {
   *    $requirements['drupal'] = array(
   *      'title' => $t('Drupal'),
   *      'value' => VERSION,
   *      'severity' => REQUIREMENT_INFO
   *    );
   *  }
   *
   *  // Test PHP version
   *  $requirements['php'] = array(
   *    'title' => $t('PHP'),
   *    'value' => ($phase == 'runtime') ? l(phpversion(), 'admin/logs/status/php') : phpversion(),
   *  );
   *  if (version_compare(phpversion(), DRUPAL_MINIMUM_PHP) < 0) {
   *    $requirements['php']['description'] = $t('Your PHP installation is too old. Drupal requires at least PHP %version.', array('%version' => DRUPAL_MINIMUM_PHP));
   *    $requirements['php']['severity'] = REQUIREMENT_ERROR;
   *  }
   *
   *  // Report cron status
   *  if ($phase == 'runtime') {
   *    $cron_last = variable_get('cron_last');
   *
   *    if (is_numeric($cron_last)) {
   *      $requirements['cron']['value'] = $t('Last run !time ago', array('!time' => format_interval(REQUEST_TIME - $cron_last)));
   *    }
   *    else {
   *      $requirements['cron'] = array(
   *        'description' => $t('Cron has not run. It appears cron jobs have not been setup on your system. Check the help pages for <a href="@url">configuring cron jobs</a>.', array('@url' => 'http://drupal.org/cron')),
   *        'severity' => REQUIREMENT_ERROR,
   *        'value' => $t('Never run'),
   *      );
   *    }
   *
   *    $requirements['cron']['description'] .= ' ' . t('You can <a href="@cron">run cron manually</a>.', array('@cron' => url('admin/logs/status/run-cron')));
   *
   *    $requirements['cron']['title'] = $t('Cron maintenance tasks');
   *  }
   */
  /* Your code here */
  return $requirements;
}




/**
 * Implements hook_menu().
 */
function securepass_menu() {
  $items = array();

  $items['admin/config/system/securepass'] = array(
    'title' => 'Securepass',
    'description' => 'Configure required settings for Securepass integration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => 'securepass_api_keys_settings'
    'access arguments' => array('administer securepass'),
    'file' => 'securepass.admin.inc',
  );

  return $items;
}



/**
 * Implements hook_help().
 */
function securepass_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module
    /*
     *case 'admin/help#block':
     *  return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page. The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second", "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas. The <a href="@blocks">blocks administration page</a> provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions.', array('@blocks' => url('admin/structure/block'))) . '</p>';

    case '':
      return '<p>' . t('', array('' => )) . '</p>';
      */
  }
}
